# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Updates match certificates"
  lane :update_match do
    if is_ci
      setup_ci
      api_key = app_store_connect_api_key(
        "key_id": ENV['APPLE_APP_STORE_API_KEY_ID'],
        "issuer_id": ENV['APPLE_APPSTORE_API_ISSUER_ID'],
        "key_content": ENV['APPLE_APP_STORE_API_KEY']
      )
    end
    if !is_ci
      api_key = app_store_connect_api_key(
        key_id: "BZ9R9Y8474",
        issuer_id: "69a6de74-e8dd-47e3-e053-5b8c7c11a4d1",
        key_filepath: "/Users/justinkumpe/Documents/AuthKey_BZ9R9Y8474.p8",
        duration: 1200, # optional (maximum 1200)
        in_house: false # optional but may be required if using match/sigh
    )
    end
    match(
      generate_apple_certs: true, 
      api_key: api_key,
      type: "appstore"
    )
    match(
      generate_apple_certs: true, 
      api_key: api_key,
      type: "development"
    )
  end

  lane :matchget do
	if is_ci
		setup_ci
	end
  match(generate_apple_certs: true, type: "development", readonly: is_ci, app_identifier: "net.justinkumpe.apps.jkuvt", git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'], git_url: "https://github.com/kumpeapps/fastlane_certs.git")
  match(generate_apple_certs: true, type: "appstore", readonly: is_ci, app_identifier: "net.justinkumpe.apps.jkuvt", git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'], git_url: "https://github.com/kumpeapps/fastlane_certs.git")
  end

  desc "Configure Flutter project without building it"
  lane :config_flutter do
    update_version

    Dir.chdir "../.." do
      sh("flutter", "build", "ios", "--release", "--no-codesign", "--config-only")
    end
  end

  desc "Build for internal testing"
  lane :build_ipa do
    config_flutter

    match(type: "development", readonly: true)
    match(type: "adhoc", readonly: true)

    gym(
      export_method: "ad-hoc",
      output_directory: "../build",
      output_name: "jkuvt.ipa",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        provisioningProfiles: { 
          "net.justinkumpe.apps.jkuvt" => "match AdHoc net.justinkumpe.apps.jkuvt"
        }
      }
    )
  end

  desc "Upload to App Store"
  lane :upload_appstore do

    match(type: "development", readonly: true)
    match(type: "appstore", readonly: true)

    gym(
      export_method: "app-store",
      output_directory: "../build",
      output_name: "jkuvt.ipa",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        provisioningProfiles: { 
          "net.justinkumpe.apps.jkuvt" => "match AppStore net.justinkumpe.apps.jkuvt"
        }
      }
    )

    app_store_connect_api_key(is_key_content_base64: true)
    
    deliver(
      skip_screenshots: true,
      skip_metadata: true,
      run_precheck_before_submit: false,
      submit_for_review: false,
      force: true
    )    
  end
end
